### ISSUE TITLE
Can't stop activity on Sugar 0.115

### ISSUE THREAD

**Issue by quozl** [sugarlabs/moon-activity#14]
Possibly related to https://github.com/sugarlabs/gwebsockets/issues/6

**Comment by Ark74** [comment]
This seems to be still on 0.118

Cold upgrading to 0.119 fix this issue?

**Comment by quozl** [comment]
No, it also happens on 0.119.  Contrary to my opening comment, it has nothing to do with https://github.com/sugarlabs/gwebsockets/issues/6 as it continues to occur despite python3-gwebsockets version 0.7-2build1 in use on Ubuntu 22.04.

**Comment by Ark74** [comment]
Alright, thank you.
Will test other fixes and come back here later on.

Regards.

**Comment by Ark74** [comment]
Hello, it's been almost a year now, and I'd like to inform that this is no longer the case on sugar 0.119 - moon 19
I've tested this on the latest Trisquel Sugar 11.0  ([manifest](http://cdimage.trisquel.org/trisquel-images/trisquel-sugar_11.0_amd64.iso.manifest))
Thanks for  your help.

**Comment by quozl** [comment]
Thanks.
