### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/moon-activity#7]
Moon is dependent on GTK+ 2 API and must be ported to GTK+ 3 API.

_(Should anybody take this, please look at my [work in progress](https://github.com/quozl/moon-activity/tree/gtk3).  Remaining changes are the Cairo drawing.)_

**Comment by chimosky** [comment]
I'm working on it.

**Comment by chimosky** [comment]
Anyone who wants to work on this should look at what I've done re Cairo drawing [here](https://github.com/chimosky/moon-activity)

**Comment by quozl** [comment]
@yashagrawal3, now that @chimosky has paused, you might want to look at this activity too.

**Comment by yell0wfl4sh** [comment]
@quozl sure!

**Comment by quozl** [comment]
Has anyone completed a port to GTK+ 3 for this activity?  Without a port to GTK+ 3, we'll have to use the port to JavaScript with Ubuntu 18.04 and later where the Sugar Toolkit for GTK+ 2 is not available.
